### ISSUE TITLE
Always installs as root and in root directory

### ISSUE THREAD

**Issue by raghuunravel** [mdklatt/ansible-python3-role#6]
Default installs to root user and I tried with become_user & sudo then it installs to root user :( 
I am using Vagarnt CentOS7 

My Playbook 
  gather_facts: yes
  become_user: vagrant
  remote_user: vagrant
  become: true
  become_method: sudo

  vars_files:
    - vars/main.yml

  roles:
    - mdklatt.python3

My Vars 
python3_pyenv: "3.5.6"
python3_command: python3.5
python3_bashrc: "/home/vagrant/.bash_profile"
python3_local: "/home/vagrant/.local/bin"

**Comment by mdklatt** [comment]
@raghuunravel 
I'm not sure I understand the problem you're having. The default should not install to the root user (`root`?) if you're using a straightforward Vagrant install.

If you want Python 3 and utilities installed for user `vagrant` on the VM, the role defaults should work. I use this for deployments to AWS and VM clusters as well, and it works as expected (I've only tested the pyenv install option on Vagrant).

Here's what I get when I run the role on a fresh Vagrant CentOS VM (bento/centos-7.5). I'm using macOS Sierra (10.12.6) running Ansible v2.6.6 as the host system.

``` yaml
- hosts: all
  
  vars:
    - python3_pyenv: "3.5.6"
    - python3_command: python3.5

  roles:
    - name: mdklatt.python3
```

This is what I see after logging in to the new VM:

<img width="649" alt="screen shot 2018-12-18 at 6 05 51 pm" src="https://user-images.githubusercontent.com/2087508/50190762-1b017e00-02f0-11e9-8487-1d36319b6937.png">

Everything is installed for user `vagrant`, as intended. Here is *~vagrant/.bash_profile*:
``` bash
# .bash_profile

# Get the aliases and functions
if [ -f ~/.bashrc ]; then
        . ~/.bashrc
fi

# User specific environment and startup programs

PATH=$PATH:$HOME/.local/bin:$HOME/bin

export PATH
# BEGIN ANSIBLE MANAGED BLOCK
export PATH="/home/vagrant/.pyenv/bin:$PATH"
eval "$(pyenv init -)"
eval "$(pyenv virtualenv-init -)"
# END ANSIBLE MANAGED BLOCK
export PATH=/home/vagrant/.local/bin:$PATH
```

One difference is that I'm just using the default values for the role variables, whereas you're explicitly defining them. The results should be the same, however.

If your intent is simply to make this work for user `vagrant`, you should not need these variables in your playbook:

``` yaml
become_user: vagrant
remote_user: vagrant
become: true
become_method: sudo
```

Other than using `become: true`, I'm not very familiar with privilege escalation in Ansible, so I'm not sure what the effect of these will be. Try using the simplified playbook I posted, and see if that helps.

**Comment by mdklatt** [comment]
No follow-up on this since last year, so considering this specific issue resolved. Multi-user installation does need to be improved for non-Vagrant installs, though, especially pyenv installs.
